// apps/react-mfe/src/app/components/cesar/cesar.tsx
// import styles from './cesar.module.scss';
import React, { useEffect, useState, useRef } from 'react';

import { Encryptions, ICesarResponse, ICesarWithKeyResponse, JAVA_CESAR_URL } from '@enc-vis-wasm-mfe/shared-types';

interface ICesarProps {
  algorithm: Encryptions;
  children?: React.ReactNode;
}

export function Cesar({ algorithm, children }: ICesarProps) {
  const [input, setInput] = useState('');
  const [key, setKey] = useState('');
  const [shift, setShift] = useState<number | null>(null);
  const [result, setResult] = useState('');
  const [cesarResults, setCesarResults] = useState<Array<ICesarResponse | ICesarWithKeyResponse>>([]);
  const teavm = useRef<any | null>(null);

  useEffect(() => {
    initJavaWASM();
  }, []);

  function initJavaWASM(): void {
    const w = window as any;

    // Workaround to force TeaVM think he is in browser, not Node.JS
    // Otherwise it will use node:fs/promises instead of fetch in load
    const savedProcess = w.process;
    try {
      delete w.process;
    } catch {}

    w.TeaVM.wasmGC
      .load(JAVA_CESAR_URL)
      .then((teavmWasm: any) => {
        teavm.current = teavmWasm;
      })
      .catch((err: any) => console.error(err))
      .finally(() => {
        if (savedProcess !== undefined) {
          w.process = savedProcess;
        }
      });
  }

  function encode(): void {
    const wasmResults: Array<ICesarResponse | ICesarWithKeyResponse> = JSON.parse(algorithm === Encryptions.Cesar ?
      teavm.current!.exports.cesarEncrypt(shift, input):
      teavm.current!.exports.cesarWithKeyEncrypt(key, input)
    );
    setCesarResults(wasmResults);

    if (algorithm === Encryptions.Cesar) {
      setResult(wasmResults[wasmResults.length - 1]?.encryptedText)
    } else {
      setResult((wasmResults as any).encryptedText)
    }
  }

  function handleSubmit(e: React.SubmitEvent<HTMLFormElement>) {
    e.preventDefault();
    encode();
  }

  return (
    <div className="flex w-full h-full bg-base-300 p-2 gap-2">
      <form className={`self-start flex flex-col bg-base-100 shadow-sm p-2 gap-3 ${algorithm === Encryptions.CesarKey ? 'flex-1' : algorithm === Encryptions.Cesar ? 'flex-initial' : ''}`} onSubmit={handleSubmit}>
        {children}
        <input className="input w-full" placeholder="Input text" value={input} onChange={e => setInput(e.target.value)}/>
        {algorithm === Encryptions.Cesar ? (
          <input className="input w-full" placeholder="Shift" type="number" min="0" onChange={e => setShift(Number(e.target.value))}/>
        ) : (
          <input className="input w-full" placeholder="Input key" value={key} onChange={e => setKey(e.target.value)}/>
        )}
        <input className="input w-full" placeholder="Result" value={result} disabled/>
        <button className="btn btn-primary w-full" type="submit">Encode</button>
      </form>
      {algorithm === Encryptions.Cesar && (
        <div className="flex-1 overflow-y-auto">
          <table className="table table-xs bg-base-100 shadow-sm">
            <thead>
              <tr>
                <th>Step</th>
                <th>Text</th>
              </tr>
            </thead>
            <tbody>
              {cesarResults.map((result, index) => (
                <tr className="hover:bg-base-200" key={index}>
                  <td>Step {index}</td>
                  <td>{ result.encryptedText }</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}

export default Cesar;

// apps/angular-mfe/src/app/components/cesar/cesar.ts
import { Component, input, signal } from '@angular/core';
import { form, FormField, required, pattern, min, validate, submit } from '@angular/forms/signals';

import { Encryptions, ICesarResponse, ICesarWithKeyResponse, JAVA_CESAR_URL } from '@enc-vis-wasm-mfe/shared-types';

interface ICardInput {
  text: string;
  key: string;
  shift: number | null;
}

@Component({
  selector: 'enc-vis-ng-mfe-cesar',
  imports: [FormField],
  templateUrl: './cesar.html',
  styleUrl: './cesar.scss',
  host: {
    'class': 'flex w-full h-full bg-base-300 p-2 gap-2',
  }
})
export class Cesar {

  algorithm = input.required<Encryptions>();

  encryptions = Encryptions;

  cesarResults = signal<Array<ICesarResponse | ICesarWithKeyResponse>>([]);

  cardInputModel = signal<ICardInput>({
    text: '',
    key: '',
    shift: null
  });

  cardInputForm = form(this.cardInputModel, (schemaPath) => {
    required(schemaPath.text);
    pattern(schemaPath.text, /^[A-Za-z]+(?:\s[A-Za-z]+)*$/);
    pattern(schemaPath.key, /^[A-Za-z]+$/);
    min(schemaPath.shift, 0);
    validate(schemaPath.shift, ({ value }) => {
      if (this.algorithm() === this.encryptions.Cesar && !value()) {
        return { kind: 'required', message: 'Shift is required' };
      }
      return null;
    });
    validate(schemaPath.key, ({ value }) => {
      if (this.algorithm() !== this.encryptions.Cesar && !value()) {
        return { kind: 'required', message: 'Key is required' };
      }
      return null;
    });
  });

  result = '';

  private teavm: any;

  constructor() {
    this.initJavaWASM();
  }

  onSubmit($event: Event): void {
    $event.preventDefault();

    submit(this.cardInputForm, async () => {
      this.encode();
    });
  }

  private encode(): void {
    const wasmResults: Array<ICesarResponse | ICesarWithKeyResponse> = JSON.parse(this.algorithm() === this.encryptions.Cesar ?
      this.teavm.exports.cesarEncrypt(this.cardInputForm.shift().value(), this.cardInputForm.text().value()):
      this.teavm.exports.cesarWithKeyEncrypt(this.cardInputForm.key().value(), this.cardInputForm.text().value())
    );

    this.cesarResults.set(wasmResults);

    if (this.algorithm() === Encryptions.Cesar) {
      this.result = wasmResults[wasmResults.length - 1]?.encryptedText;
    } else {
      this.result = (wasmResults as any).encryptedText;
    }
  }

  private initJavaWASM(): void {
    const w = window as any;

    // Workaround to force TeaVM think he is in browser, not Node.JS
    // Otherwise it will use node:fs/promises instead of fetch in load
    const savedProcess = w.process;
    try {
      delete w.process;
    } catch {}

    w.TeaVM.wasmGC
      .load(JAVA_CESAR_URL)
      .then((teavm: any) => {
        this.teavm = teavm;
      })
      .catch((err: any) => console.error(err))
      .finally(() => {
        if (savedProcess !== undefined) {
          w.process = savedProcess;
        }
      });
  }
}
